definitions:
  config:
    /hst:hst/hst:configurations:
      /common:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: ['../hst:defaults', '../visitscotland/hst:workspace']
        /hst:abstractpages:
          jcr:primaryType: hst:pages
        /hst:pages:
          jcr:primaryType: hst:pages
        /hst:components:
          jcr:primaryType: hst:components
        /hst:templates:
          jcr:primaryType: hst:templates
          /base-layout:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/visitscotland/base/base-layout.ftl
          /base-top-menu:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/visitscotland/base/base-top-menu.ftl
          /base-footer:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/visitscotland/base/base-footer.ftl
          /homepage-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/visitscotland/pages/homepage-main.ftl
          /pagenotfound-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/visitscotland/pages/pagenotfound-main.ftl
          /breadcrumb:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/visitscotland/modules/breadcrumb/breadcrumb.ftl
          /itinerary:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/visitscotland/pages/itinerary-main.ftl
          /listicle:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/visitscotland/pages/listicle-main.ftl
          /destination:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/visitscotland/pages/destination-main.ftl
          /utility-footer:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/visitscotland/base/utility-footer.ftl
          /vuex-example:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/visitscotland/dev-pages/vuex-example.ftl
          /general-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/visitscotland/pages/general-main.ftl
          /internal:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/visitscotland/base/internal.ftl
          /internal-css-header:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/visitscotland/base/internal/css-header.ftl
          /internal-header:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/visitscotland/base/internal/header.ftl
          /internal-script-footer:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/visitscotland/base/internal/script-footer.ftl
          /internal-footer:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/visitscotland/base/internal/footer.ftl
        /hst:catalog:
          jcr:primaryType: hst:catalog
          /visitscotland-catalog:
            jcr:primaryType: hst:containeritempackage
      /visitscotland:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../vs-default]
      /visitscotland-es:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../vs-default, '../vs-default/hst:workspace']
      /visitscotland-fr:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../vs-default, '../vs-default/hst:workspace']
      /visitscotland-de:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../vs-default, '../vs-default/hst:workspace']
      /visitscotland-nl:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../vs-default, '../vs-default/hst:workspace']
      /visitscotland-it:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../vs-default, '../vs-default/hst:workspace']
      /vs-default:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../common, '../visitscotland/hst:workspace']
      /business-events-freemarker:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../business-events]
      /business-events:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../common]
